export const PLAYLIST_MOBILE_ROWS_PER_PAGE_OPTIONS = [15, 25, 50, 100]
export const PLAYLIST_LIST_ROWS_PER_PAGE_OPTIONS =
  PLAYLIST_MOBILE_ROWS_PER_PAGE_OPTIONS
export const PLAYLIST_DESKTOP_ROWS_PER_PAGE_OPTIONS = [50, 100, 250, 500]
export const PLAYLIST_PER_PAGE_STORAGE_KEY = 'playlist.perPage'
export const PLAYLIST_LIST_PER_PAGE_STORAGE_KEY = 'playlists.perPage'
export const DEFAULT_PLAYLIST_PER_PAGE = 50
