export const PLAYLIST_MOBILE_ROWS_PER_PAGE_OPTIONS = [15, 25, 50, 100]
export const PLAYLIST_MOBILE_PER_PAGE_STORAGE_KEY = 'playlist.perPage'
export const DEFAULT_PLAYLIST_MOBILE_PER_PAGE = 50
export const PLAYLIST_DESKTOP_ROWS_PER_PAGE_OPTIONS = [100, 250, 500]
